# Generated by Django 4.2.1 on 2023-05-29 17:28

from django.db import migrations
from django.contrib.auth.models import Group


def forwards(apss, schema_editor):
    Group.objects.create(name="customer")
    Group.objects.create(name="company")


def backwards(apss, schema_editor):
    Group.objects.filter(name="customer").delete()
    Group.objects.filter(name="company").delete()


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(code=forwards, reverse_code=backwards),
    ]
