# Generated by Django 4.2.1 on 2023-06-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coursebookapp", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("photo", models.ImageField(blank=True, upload_to="instructors/")),
                (
                    "app_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructors_created",
                        to="coursebookapp.appuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("short_description", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("dolnośląskie", "Dolnośląskie"),
                            ("kujawsko-pomorskie", "Kujawsko-Pomorskie"),
                            ("lubelskie", "Lubelskie"),
                            ("lubuskie", "Lubuskie"),
                            ("łódzkie", "Łódzkie"),
                            ("małopolskie", "Małopolskie"),
                            ("mazowieckie", "Mazowieckie"),
                            ("opolskie", "Opolskie"),
                            ("podkarpackie", "Podkarpackie"),
                            ("podlaskie", "Podlaskie"),
                            ("pomorskie", "Pomorskie"),
                            ("śląskie", "Śląskie"),
                            ("świętokrzyskie", "Świętokrzyskie"),
                            ("warmińsko-mazurskie", "Warmińsko-Mazurskie"),
                            ("wielkopolskie", "Wielkopolskie"),
                            ("zachodniopomorskie", "Zachodniopomorskie"),
                        ],
                        max_length=30,
                    ),
                ),
                ("available", models.BooleanField(default=False)),
                ("seats", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("time_start", models.TimeField()),
                ("city", models.CharField(max_length=100)),
                ("course_description", models.TextField()),
                ("course_for", models.TextField()),
                ("course_benefit", models.TextField()),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="coursebookapp.instructor",
                    ),
                ),
            ],
        ),
    ]
