# Generated by Django 4.2.1 on 2023-07-29 15:28

import coursebookapp.models.course_image
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coursebookapp", "0003_instructor_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=coursebookapp.models.course_image.CourseImage.get_upload_path
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coursebookapp.course",
                    ),
                ),
            ],
        ),
    ]
