# Generated by Django 4.2.1 on 2023-08-01 17:18

import coursebookapp.models.instructor
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coursebookapp", "0004_courseimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="province_slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to=coursebookapp.models.instructor.Instructor.get_upload_path,
            ),
        ),
    ]
