# Generated by Django 4.2.1 on 2023-11-12 19:01

import coursebookapp.models.blog_post
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coursebookapp", "0007_cart_purchasedcourse_cartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("short_content", models.TextField()),
                ("content", models.TextField()),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=coursebookapp.models.blog_post.BlogPost.get_upload_path,
                    ),
                ),
                (
                    "photo_thumb",
                    models.ImageField(
                        blank=True,
                        upload_to=coursebookapp.models.blog_post.BlogPost.get_upload_path,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="coursebookapp.blogcategory"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coursebookapp.appuser",
                    ),
                ),
            ],
        ),
    ]
