from .home_view import HomeView
from .success_view import SuccessView
from .cancel_view import CancelView
from .user_login_view import UserLoginView
from .user_logout_view import UserLogoutView
from .register_view import RegisterView
from .account_view import AccountView
from .account_courses_view import AccountCoursesView
from .account_instructors_view import AccountInstructorsView
from .account_instructors_delete import AccountInstructorDelete
from .account_courses_delete import AccountCourseDelete
from .course_detail_view import CourseDetailView
from .course_category_view import CourseCategoryView
from .edit_instructor_view import EditInstructorView
from .edit_course_view import EditCourseView
from .add_to_cart import AddToCartView
from .add_to_cart import IncreaseCartItemQuantityView
from .remove_from_cart import RemoveFromCartView
from .cart import CartView
from .mini_cart import MiniCartView
from .create_checkout_session import CreateCheckoutSession
from .account_blog_view import AccountBlogView
from .account_blog_modify_view import BlogPostModify
from .post_view import PostDetailView
from .blog_view import BlogCategoryView
from .course_api_view import ActiveCoursesListView
from .course_api_view import ActiveProvincesListView
from .course_api_view import CoursesByProvinceSlugView
from .webhook import stripe_webhook
from .contact import ContactView
from .about_us import AboutUsView
from .faq import FaqView
from .gallery import GalleryView
from .newest_view import NewestView
from .order_details import OrderDetailsView

# from .account_courses_delete import delete_course
